services:
  mysql:
    image: mysql:8.4
    container_name: notes
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: notes
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
